UPSTREAM: sys: device_mmio: add devcie_map for !DEVICE_MMIO_IS_IN_RAM
commit fdca7582708c93c46788f6977ceb19a266918146 upstream.

On !MMU && !PCIE && !EXTERNAL_ADDRESS_TRANSLATION platforms, the
device_map() isn't defined, thus brings below ramconsole build error:

ram_console.c: In function 'ram_console_init':
ram_console.c:49:9: error: implicit declaration of function 'device_map'

Previously, I solved this issue in a workaround style[1] as below:

+#ifndef DEVICE_MMIO_IS_IN_RAM
+#define device_map(virt, phys, size, flags) *(virt) = (phys)
+#endif /* DEVICE_MMIO_IS_IN_RAM */

But during the PR review progress, pathcing device_mmio.h is suggested.
This patch implements that suggestion.

Link: https://github.com/zephyrproject-rtos/zephyr/pull/97894 [1]
Signed-off-by: Jisheng Zhang <jszhang@kernel.org>